# Site settings
title: AWSHUB,
tagline: a comidade AWS se encontra aqui!
description: > # this means to ignore newlines until "baseurl:"
  Site da comunidade AWS com Blog, Tutoriais, Meetups, Oportunidades e mais!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://awshub.com.br" # the base hostname & protocol for your site
twitter_username: awscloud
meetupsp_link: https://www.meetup.com/pt-BR/Sao-Paulo-Amazon-Web-Services-AWS-Meetup/
email: awsmeetup@gmail.com

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
